name: Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    if: github.actor == 'jonatasolmartins' || github.actor == 'co-maintainer'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack SmartStrings/SmartStrings.csproj --configuration Release --no-build

      - name: Publish to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v') # Only publish on version tags
        run: dotnet nuget push SmartStrings/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json